clear;

%%%observe how CMSIS FIR low pass filter effect the test data
fileID_coefficient = fopen('coefficient.txt','r');
formatSpec = '%f';
size_coefficient = [1 Inf];
FIR_filter = fscanf(fileID_coefficient,formatSpec,size_coefficient);
fclose(fileID_coefficient);
FIR_low_pass = fftshift(fft(FIR_filter));
FIR_low_pass_abs = abs(FIR_low_pass);

fileID_test_input = fopen('test_in.txt','r'); %input test signal
formatSpec = '%f';
size_of_input = [1 Inf];
test_input = fscanf(fileID_test_input,formatSpec,size_of_input);
fclose(fileID_test_input);
for i=1:320
    test_input_list(i)=test_input(i);
end
test_input_fourier_abs=abs(fftshift(fft(test_input_list)));
www = linspace(-24000, 24000, 320)';

fileID_test_output = fopen('test_out.txt','r');
formatSpec = '%f';
size_test_output = [1 Inf];
test_output_given_by_Mbed = fscanf(fileID_test_output,formatSpec,size_test_output);
fclose(fileID_test_output);
test_output_freq_abs = abs(fftshift(fft(test_output_given_by_Mbed)));

%%%draw first plot
figure
subplot(2,2,1), plot(test_input_list);
xlabel('sample time (rate=48kHz)')
ylabel('Sampled values')
title('Test input signal, in time domain')
subplot(2,2,2), plot(www, test_input_fourier_abs);
axis([0 24000 0 150]) 
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Test input signal, in frequency domain')
subplot(2,2,3), plot(test_output_given_by_Mbed);
xlabel('sample time (rate = 48kHz)')
ylabel('Values')
title('Test output signal given by Mbed, in time domain')
subplot(2,2,4), plot(www, test_output_freq_abs);
axis([0 24000 0 150]) 
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Test output signal given by Mbed, in frequency domain')

%%%compare how CMSIS FIR low pass filter and matlab's FIR LP filter effect the test data
h = fir1(28, 6/24); %FIR generated by Matlab
test_output_signal_by_matlab_filter = filter(h,1,test_input_list);
test_output_fourier_by_matlab_abs=abs(fftshift(fft(test_output_signal_by_matlab_filter)));

test_output_signal_by_FIR_filter = filter(FIR_filter,1,test_input_list);
test_output_fourier_by_FIR_abs=abs(fftshift(fft(test_output_signal_by_FIR_filter)));

figure
subplot(2,2,1), plot(test_output_signal_by_FIR_filter);
xlabel('sample time (rate=48kHz)')
ylabel('Values')
title('Test output signal generated by FIR Low-Pass filter, in time domain')
subplot(2,2,2), plot(www, test_output_fourier_by_FIR_abs);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Test output signal generated by FIR Low-Pass filter, in frequency domain')
axis([0 24000 0 150]) 
subplot(2,2,3), plot(test_output_signal_by_matlab_filter);
xlabel('sample time (rate=48kHz)')
ylabel('Values')
title("Test output signal generated by Matlab's Low-Pass filter, in time domain")
subplot(2,2,4), plot(www, test_output_fourier_by_matlab_abs);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title("Test output signal generated by Matlab's Low-Pass filter, in frequency domain")
axis([0 24000 0 150])

%%test the gyro data
%%%compare how CMSIS FIR low pass filter and matlab's FIR LP filter effect
%%%the gyro data
fileID = fopen('gyro1in.txt','r'); %gyro input
formatSpec = '%f';
gyro_input_size = [3 320];
gyro_input = fscanf(fileID,formatSpec,gyro_input_size);
fclose(fileID);

for i=1:320
    x(i) = gyro_input(1,i);
    y(i) = gyro_input(2,i);
    z(i) = gyro_input(3,i);
end

fileIDD = fopen('gyro1out.txt','r');
formatSpec = '%f';
sizeB = [3 320];
gyro_output_by_mbed = fscanf(fileIDD,formatSpec,sizeB);

for i=1:320
    x_output_by_mbed(i) = gyro_output_by_mbed(1,i);
    y_output_by_mbed(i) = gyro_output_by_mbed(2,i);
    z_output_by_mbed(i) = gyro_output_by_mbed(3,i);
end


x_output_by_matlab = filter(h, 1, x);
y_output_by_matlab = filter(h, 1, y);
z_output_by_matlab = filter(h, 1, z);


%We compare the frequency domain of different outputs.
X_output_mbed_freq_magnitude = abs((fftshift(fft(x_output_by_mbed))));
Y_output_mbed_freq_magnitude = abs((fftshift(fft(y_output_by_mbed))));
Z_output_mbed_freq_magnitude = abs((fftshift(fft(z_output_by_mbed))));

X_output_matlab_freq_magnitude = abs((fftshift(fft(x_output_by_matlab))));
Y_output_matlab_freq_magnitude = abs((fftshift(fft(y_output_by_matlab))));
Z_output_matlab_freq_magnitude = abs((fftshift(fft(z_output_by_matlab))));

w = linspace(-50, 50, 320)'; %since our sampling frequency is 100 hz.

figure
subplot(2,3,1), plot(w, X_output_mbed_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro X signal(by Mbed)');
axis([0 50 0 5*10^6])
subplot(2,3,2), plot(w, Y_output_mbed_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro Y signal(by Mbed)');
axis([0 50 0 2*10^7])
subplot(2,3,3), plot(w, Z_output_mbed_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro Z signal(by Mbed)');
axis([0 50 0 5*10^6])
subplot(2,3,4), plot(w, X_output_matlab_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro X signal(by Matlab FIR)');
axis([0 50 0 5*10^6])
subplot(2,3,5), plot(w, Y_output_matlab_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro Y signal(by Matlab FIR)');
axis([0 50 0 2*10^7])
subplot(2,3,6), plot(w, Z_output_matlab_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro Z signal(by Matlab FIR)');
axis([0 50 0 5*10^6])